import * as Factory from "factory.ts";
import { MockedResponse } from "@apollo/client/testing";
import { GET_CLIENTS } from "./queries";

export const ClientMock = Factory.Sync.makeFactory({
  __typename: "Client",
  id: 1,
  cli_id: 111898,
  cli_reference: "C00001390",
  cli_trader_id: 0,
  cli_cold_caller_id: 0,
  cli_affiliate_id: -1,
  cli_affiliate2_id: null,
  cli_type_id: 2,
  cli_name: "CLEAR CURRENCY LLP",
  cli_address1: "4TH FLOOR DAUNTSEY HOUSE",
  cli_address2: "England | London Inner",
  cli_address3: "",
  cli_postcode: "EC2R 8AB",
  cli_city: "LONDON",
  cli_country_id: -1,
  cli_fax: "",
  cli_switchboard: "",
  cli_creation_date: "20210421",
  cli_company_sic: "",
  cli_company_number: "GBOC353894",
  cli_status_id: 1,
  cli_email: "test-users+signup@clearcurrency.co.uk",
  cli_web: "TEST",
  cli_primary_contact_id: 24789,
  cli_alert: 0,
  cli_comment: "Online registration 21/04/2021 13:55\r\n\r\nClear Treasury",
  cli_old_reference: "",
  cli_trader_commission: "0",
  cli_archived: 0,
  cli_web_login: "test-users+signup@clearcurrency.co.uk",
  cli_web_password: "",
  cli_web_commission: 0.0,
  cli_web_disable_trading: 0,
  cli_web_must_change_pwd: null,
  cli_account_verified: 1,
  cli_call_back_date: "20210421",
  cli_call_back_time: "",
  cli_call_back_alert: 0,
  cli_callback_priority_id: 4,
  cli_competitor_note: "",
  cli_activity_id: -1,
  cli_profit_limit: 0,
  cli_referer: "",
  cli_unsubscribe_emails: 1,
  cli_default_charge: "",
  cli_ding_type: "",
  cli_kyc_source: "",
  cli_kyc_nature: "Finance & Insurance",
  cli_kyc_country_origin_id: 0,
  cli_kyc_avg_trade_size: "0",
  cli_kyc_max_trade_size: "0",
  cli_kyc_annual_volume: "10000",
  cli_kyc_frequency: "Daily",
  cli_kyc_risk_profile: "",
  cli_kyc_ccy: "",
  cli_kyc_authorised: 0,
  cli_company_id: 0,
  cli_admin_note: "",
  cli_cold_caller_commission: "0",
  cli_note1: "",
  cli_note2: "",
  cli_affiliate1_commission: "0",
  cli_affiliate2_commission: "0",
  cli_pool_commission: "0",
  cli_registration_cost: "0",
  cli_registred_IP_address: "",
  cli_language_id: 1003,
  cli_kyc_pep: 0,
  cli_kyc_fatca: 0,
  cli_kyc_unlocked_until: "",
  cli_cos_id: 0,
  cli_start_business_date: "",
  cli_balance_sheet: "0",
  cli_companies_house_up_to_date: 0,
  cli_kyc_hpi: 0,
  cli_can_trade_forward: 0,
  cli_max_open_position: "0",
  cli_max_open_position_ccy: "",
  cli_is_internal: 0,
  cli_legal_status_id: 0,
  cli_in_administration: 0,
  cli_trading_as_name: "",
  cli_trading_address1: "",
  cli_trading_address2: "",
  cli_trading_address3: "",
  cli_trading_city: "",
  cli_trading_postcode: "",
  cli_trading_country_id: 0,
  cli_company_vat: "",
  cli_reason: "Paying suppliers",
  cli_kyc_source_of_wealth: "",
  cli_kyc_Relationship_with_beneficiaries: "",
  cli_agree_marketing_conditions: 1,
  cli_agree_marketing_conditions_affiliates: 1,
  cli_forward_margin: "0",
  cli_credit_limit: "0",
  cli_beneficiary_special_permission: 0,
  cli_credit_agreement: 0,
  cli_credit_percentage: "0",
  cli_kyc_complex_ownership_chain: 0,
  cli_kyc_face_to_face: 0,
  cli_kyc_adverse_news: 0,
  cli_kyc_bearer_shares: 0,
  cli_industry_group_id: -1,
  cli_override_risk_profile: 0,
  cli_incorporated_under_id: 0,
  cli_kyc_note: "",
  cli_web_disable_instructions: 0,
  cli_license_expiry_date: "",
  cli_regulator_name: "",
  cli_web_currency_threshold_template_id: 0,
  cli_web_disable_statement: null,
  cli_web_currency_threshold_template_overnight_id: null,
  cli_operator_id: null,
  cli_trading_status_id: null,
  cli_kyc_non_UK_shareholder: 0,
  cli_inc_avg_trade_size: null,
  cli_inc_annual_volume: null,
  cli_inc_frequency: null,
  cli_inc_ccy: null,
  cli_inc_max_trade_size: null,
  cli_manager_id: null,
  cli_web_tfa: "",
  cli_trust_pilot: null,
});

export const clientsQueryMock: MockedResponse = {
  request: {
    query: GET_CLIENTS,
  },
  result: {
    data: {
      clients: ClientMock.buildList(2),
    },
  },
};
